.PHONY: lint
lint:
	curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $$(go env GOPATH)/bin
	go install ./...
	go test -i ./...
	$$(go env GOPATH)/bin/golangci-lint run ./...
